blank_issues_enabled: false
contact_links:
  - name: Telegram Support
    url: https://t.me/redf0x1
    about: Chat with us on Telegram for quick support
  - name: Website
    url: https://ohmyshot.app
    about: Visit our official website
